"""Serialize the live DB inventory back into a deterministic ``systems.toml`` (ADR-0199, #640).

This is the full-inventory generalization of ADR-0115 §6's cost-class-only export. It reads the
live config-owned rows (``image_catalog`` / ``resources`` / ``build_hosts`` /
``cost_class_coefficients``), honors the override ledger (``removed`` identities omitted,
``detached`` identities emitted with their live runtime values), and renders one deterministic
``systems.toml`` document so an operator can capture runtime state back into the version-controlled
file and reproduce the fleet on a fresh start.

Two halves, split so sub-issue D (ConfigMap/file writeback) can persist the text and unit-test the
pure serializer with a hand-built snapshot:

* :func:`read_inventory_snapshot` — DB I/O + ledger lookup → an :class:`InventorySnapshot`.
* :func:`serialize_inventory` — pure :class:`InventorySnapshot` → deterministic TOML text.

The connection/debug fields the remote-libvirt provider reads straight from the file (``gdb_addr``,
``gdbstub_range``, the three TLS secret refs, ``base_image``, ``shapes``) are **not** persisted in
``resources`` (the field-persistence audit; see the spec), so a ``[[remote_libvirt]]`` block is a
**skeleton**: those fields are emitted as ``REPLACE_ME_*`` placeholders an operator must complete
before a fresh start. An unedited ``remote_libvirt`` skeleton does not parse.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import TYPE_CHECKING

from kdive.domain.catalog.resource_capabilities import (
    CONCURRENT_ALLOCATION_CAP_KEY,
    MEMORY_MB_KEY,
    VCPUS_KEY,
)
from kdive.domain.catalog.resources import ResourceKind
from kdive.inventory.overrides import (
    BUILD_HOST_RESOURCE_KIND,
    InventoryOverrideDisposition,
    InventorySourceKind,
    lookup_many,
)

if TYPE_CHECKING:
    from collections.abc import Mapping

    from psycopg import AsyncConnection

    from kdive.inventory.overrides import InventoryOverride

__all__ = [
    "ImageRow",
    "ResourceRow",
    "BuildHostRow",
    "InventorySnapshot",
    "REMOTE_PLACEHOLDER_PREFIX",
    "read_inventory_snapshot",
    "serialize_inventory",
]

_CONFIG_MANAGED_BY = "config"

# The shared marker every export placeholder starts with. The writeback skeleton guard (#641)
# imports this so it and the serializer cannot drift: a document containing this marker is an
# incomplete skeleton that must not be persisted as a live source.
REMOTE_PLACEHOLDER_PREFIX = "REPLACE_ME_"

# The fixed placeholder sentinels for the remote-libvirt file-only fields. Deliberately obvious
# (not realistic secrets) so a secret scanner does not trip and an operator cannot miss them.
_REMOTE_PLACEHOLDERS: dict[str, str] = {
    "gdb_addr": f"{REMOTE_PLACEHOLDER_PREFIX}gdb_addr",
    "gdbstub_range": f"{REMOTE_PLACEHOLDER_PREFIX}gdbstub_range",
    "client_cert_ref": f"{REMOTE_PLACEHOLDER_PREFIX}client_cert_ref",  # pragma: allowlist secret
    "client_key_ref": f"{REMOTE_PLACEHOLDER_PREFIX}client_key_ref",  # pragma: allowlist secret
    "ca_cert_ref": f"{REMOTE_PLACEHOLDER_PREFIX}ca_cert_ref",  # pragma: allowlist secret
    "base_image": f"{REMOTE_PLACEHOLDER_PREFIX}base_image",
}

_HEADER = (
    "# Generated by ops.export_systems_toml — a values-only snapshot of the live inventory.\n"
    "# It captures persisted state (images, build_hosts, cost_classes, and the identity/\n"
    "# economic/sizing fields of resources). It is NOT a complete config:\n"
    "#\n"
    "#   * Each [[remote_libvirt]] block is a SKELETON. The provider reads gdb_addr,\n"
    "#     gdbstub_range, the three TLS refs (client_cert_ref/client_key_ref/ca_cert_ref),\n"
    "#     base_image, and shapes straight from this file; they are not stored in the DB, so\n"
    "#     they are emitted as REPLACE_ME_* placeholders. Replace every REPLACE_ME_* value\n"
    "#     before a fresh start (set base_image to one of the [[image]] names below). An\n"
    "#     unedited skeleton does not parse.\n"
    "#   * A [[image]] in the 'defined' state (no built object yet) is emitted with a\n"
    "#     REPLACE_ME_object_key placeholder; its original build base/components are not\n"
    "#     stored in the DB.\n"
)


# ---- snapshot rows --------------------------------------------------------------------


@dataclass(frozen=True)
class ImageRow:
    """A config-owned ``image_catalog`` row, as the serializer needs it."""

    provider: str
    name: str
    arch: str
    format: str
    root_device: str
    visibility: str
    capabilities: list[str]
    object_key: str | None
    digest: str | None
    volume: str | None
    state: str
    # A local-libvirt staged-path source (ADR-0228); defaulted so existing constructors are
    # unchanged. Mutually exclusive with object_key/volume (DB image_object_present CHECK).
    path: str | None = None


@dataclass(frozen=True)
class ResourceRow:
    """A config-owned ``resources`` row (remote-libvirt / local-libvirt / fault-inject).

    ``seed`` is fault-inject only (file-only, defaulted); ``None`` for the other kinds.
    """

    name: str
    cost_class: str
    pool: str
    host_uri: str
    vcpus: int | None
    memory_mb: int | None
    concurrent_allocation_cap: int
    seed: int | None


@dataclass(frozen=True)
class BuildHostRow:
    """A config-owned ``build_hosts`` row."""

    name: str
    kind: str
    base_image_volume: str | None
    workspace_root: str
    max_concurrent: int


@dataclass(frozen=True)
class InventorySnapshot:
    """The live config-owned inventory the serializer renders."""

    images: tuple[ImageRow, ...]
    remote_libvirt: tuple[ResourceRow, ...]
    local_libvirt: tuple[ResourceRow, ...]
    fault_inject: tuple[ResourceRow, ...]
    build_hosts: tuple[BuildHostRow, ...]
    cost_classes: tuple[tuple[str, Decimal], ...]


# ---- TOML emitter primitives ----------------------------------------------------------

_TOML_ESCAPES = {
    "\\": "\\\\",
    '"': '\\"',
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
    "\b": "\\b",
    "\f": "\\f",
}


def _toml_str(value: str) -> str:
    """Emit ``value`` as a TOML basic string with full escaping (injection-safe).

    Every control character (and ``"`` / ``\\`` / newline / tab) is escaped, so a value
    containing a quote or newline can never break out of its string and inject a sibling key.
    """
    out = ['"']
    for ch in value:
        escaped = _TOML_ESCAPES.get(ch)
        if escaped is not None:
            out.append(escaped)
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _toml_array(items: list[str]) -> str:
    """Emit a list of strings as a TOML inline array with escaped elements."""
    if not items:
        return "[]"
    return "[" + ", ".join(_toml_str(item) for item in items) + "]"


def _toml_int(value: int) -> str:
    """Emit an integer as a bare TOML integer."""
    return str(value)


# ---- serialize_inventory (pure) -------------------------------------------------------


def serialize_inventory(snapshot: InventorySnapshot) -> str:
    """Render ``snapshot`` as a deterministic ``systems.toml`` document.

    Byte-identical for a given snapshot: a fixed section order, each collection sorted by its
    identity key, a fixed key order per block, and no clock/timestamp content. A NULL optional
    column is omitted (never emitted blank), so the output round-trips through reconcile.

    Args:
        snapshot: The live config-owned inventory to serialize.

    Returns:
        The ``systems.toml`` text.
    """
    parts: list[str] = [_HEADER, "schema_version = 2\n"]
    for image in sorted(snapshot.images, key=lambda r: (r.provider, r.name, r.arch)):
        parts.append(_emit_image(image))
    for host in sorted(snapshot.remote_libvirt, key=lambda r: r.name):
        parts.append(_emit_remote(host))
    for host in sorted(snapshot.local_libvirt, key=lambda r: r.name):
        parts.append(_emit_local(host))
    for host in sorted(snapshot.fault_inject, key=lambda r: r.name):
        parts.append(_emit_fault(host))
    for build_host in sorted(snapshot.build_hosts, key=lambda r: r.name):
        parts.append(_emit_build_host(build_host))
    for name, coeff in sorted(snapshot.cost_classes, key=lambda c: c[0]):
        parts.append(_emit_cost_class(name, coeff))
    return "\n".join(parts)


def _emit_image(image: ImageRow) -> str:
    lines = [
        "[[image]]",
        f"provider = {_toml_str(image.provider)}",
        f"name = {_toml_str(image.name)}",
        f"arch = {_toml_str(image.arch)}",
        f"format = {_toml_str(image.format)}",
        f"root_device = {_toml_str(image.root_device)}",
        f"visibility = {_toml_str(image.visibility)}",
        f"capabilities = {_toml_array(image.capabilities)}",
    ]
    lines.extend(_emit_image_source(image))
    return "\n".join(lines) + "\n"


def _emit_image_source(image: ImageRow) -> list[str]:
    """Reconstruct the ``[image.source]`` table from ``(object_key, volume, path, state)``.

    A ``path`` is a local-libvirt ``staged-path`` source (ADR-0228); a ``volume`` is a ``staged``
    source; an ``object_key`` is an ``s3`` source (with the digest iff present); a ``defined`` row
    with none is emitted as an ``s3`` skeleton with a placeholder ``object_key`` (its original
    build base is not stored — see the header).
    """
    if image.path is not None:
        return ["[image.source]", 'kind = "staged-path"', f"path = {_toml_str(image.path)}"]
    if image.volume is not None:
        return ["[image.source]", 'kind = "staged"', f"volume = {_toml_str(image.volume)}"]
    if image.object_key is not None:
        lines = ["[image.source]", 'kind = "s3"', f"object_key = {_toml_str(image.object_key)}"]
        if image.digest is not None:
            lines.append(f"digest = {_toml_str(image.digest)}")
        return lines
    return [
        "[image.source]",
        'kind = "s3"',
        f"object_key = {_toml_str(f'{REMOTE_PLACEHOLDER_PREFIX}object_key')}",
    ]


def _emit_remote(host: ResourceRow) -> str:
    lines = [
        "[[remote_libvirt]]",
        f"name = {_toml_str(host.name)}",
        f"cost_class = {_toml_str(host.cost_class)}",
        f"pool = {_toml_str(host.pool)}",
        f"concurrent_allocation_cap = {_toml_int(host.concurrent_allocation_cap)}",
        f"uri = {_toml_str(host.host_uri)}",
        f"vcpus = {_toml_int(_require_int(host.vcpus, host.name, 'vcpus'))}",
        f"memory_mb = {_toml_int(_require_int(host.memory_mb, host.name, 'memory_mb'))}",
        f"gdb_addr = {_toml_str(_REMOTE_PLACEHOLDERS['gdb_addr'])}",
        f"gdbstub_range = {_toml_str(_REMOTE_PLACEHOLDERS['gdbstub_range'])}",
        f"client_cert_ref = {_toml_str(_REMOTE_PLACEHOLDERS['client_cert_ref'])}",
        f"client_key_ref = {_toml_str(_REMOTE_PLACEHOLDERS['client_key_ref'])}",
        f"ca_cert_ref = {_toml_str(_REMOTE_PLACEHOLDERS['ca_cert_ref'])}",
        f"base_image = {_toml_str(_REMOTE_PLACEHOLDERS['base_image'])}",
        "shapes = []",
    ]
    return "\n".join(lines) + "\n"


def _emit_local(host: ResourceRow) -> str:
    lines = [
        "[[local_libvirt]]",
        f"name = {_toml_str(host.name)}",
        f"cost_class = {_toml_str(host.cost_class)}",
        f"pool = {_toml_str(host.pool)}",
        f"concurrent_allocation_cap = {_toml_int(host.concurrent_allocation_cap)}",
        f"host_uri = {_toml_str(host.host_uri)}",
    ]
    return "\n".join(lines) + "\n"


def _emit_fault(host: ResourceRow) -> str:
    lines = [
        "[[fault_inject]]",
        f"name = {_toml_str(host.name)}",
        f"cost_class = {_toml_str(host.cost_class)}",
        f"pool = {_toml_str(host.pool)}",
        f"concurrent_allocation_cap = {_toml_int(host.concurrent_allocation_cap)}",
        f"vcpus = {_toml_int(_require_int(host.vcpus, host.name, 'vcpus'))}",
        f"memory_mb = {_toml_int(_require_int(host.memory_mb, host.name, 'memory_mb'))}",
        f"seed = {_toml_int(host.seed if host.seed is not None else 0)}",
    ]
    return "\n".join(lines) + "\n"


def _emit_build_host(build_host: BuildHostRow) -> str:
    lines = [
        "[[build_host]]",
        f"name = {_toml_str(build_host.name)}",
        f"kind = {_toml_str(build_host.kind)}",
        f"workspace_root = {_toml_str(build_host.workspace_root)}",
        f"max_concurrent = {_toml_int(build_host.max_concurrent)}",
    ]
    if build_host.base_image_volume is not None:
        lines.append(f"base_image_volume = {_toml_str(build_host.base_image_volume)}")
    return "\n".join(lines) + "\n"


def _emit_cost_class(name: str, coeff: Decimal) -> str:
    # ADR-0115 §6 idiom: coeff is a quoted string for an exact round-trip.
    return f"[[cost_class]]\nname = {_toml_str(name)}\ncoeff = {_toml_str(str(coeff))}\n"


def _require_int(value: int | None, name: str, field: str) -> int:
    if value is None:
        raise ValueError(f"resource {name!r} is missing the required {field} capability")
    return value


# ---- read_inventory_snapshot (DB read + ledger honoring) ------------------------------


async def read_inventory_snapshot(conn: AsyncConnection) -> InventorySnapshot:
    """Read the live config-owned inventory into an :class:`InventorySnapshot`.

    Honors the override ledger (ADR-0199): an identity carrying a ``removed`` entry is omitted (a
    cordoned-live ``removed`` row keeps ``managed_by='config'`` until GC, so it must be filtered
    out here); a ``detached`` identity passes through with its live runtime values (which is
    exactly the modify the export captures). Read-only; takes no lock.

    Args:
        conn: A live connection.

    Returns:
        The config-owned inventory snapshot, ledger-filtered.
    """
    resource_overrides = await lookup_many(conn, InventorySourceKind.RESOURCE)
    build_host_overrides = await lookup_many(conn, InventorySourceKind.BUILD_HOST)
    return InventorySnapshot(
        images=await _read_images(conn),
        remote_libvirt=await _read_resources(conn, ResourceKind.REMOTE_LIBVIRT, resource_overrides),
        local_libvirt=await _read_resources(conn, ResourceKind.LOCAL_LIBVIRT, resource_overrides),
        fault_inject=await _read_resources(conn, ResourceKind.FAULT_INJECT, resource_overrides),
        build_hosts=await _read_build_hosts(conn, build_host_overrides),
        cost_classes=await _read_cost_classes(conn),
    )


def _is_removed(
    overrides: Mapping[tuple[str, str], InventoryOverride], resource_kind: str, name: str
) -> bool:
    entry = overrides.get((resource_kind, name))
    return entry is not None and entry.disposition is InventoryOverrideDisposition.REMOVED


async def _read_images(conn: AsyncConnection) -> tuple[ImageRow, ...]:
    rows: list[ImageRow] = []
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT provider, name, arch, format, root_device, visibility, capabilities, "
            "object_key, digest, volume, path, state "
            "FROM image_catalog WHERE managed_by = %s",
            (_CONFIG_MANAGED_BY,),
        )
        fetched = await cur.fetchall()
    for raw in fetched:
        (
            provider,
            name,
            arch,
            fmt,
            root_device,
            visibility,
            capabilities,
            object_key,
            digest,
            volume,
            path,
            state,
        ) = raw
        rows.append(
            ImageRow(
                provider=str(provider),
                name=str(name),
                arch=str(arch),
                format=str(fmt),
                root_device=str(root_device),
                visibility=str(visibility),
                capabilities=[str(cap) for cap in capabilities],
                object_key=None if object_key is None else str(object_key),
                digest=None if digest is None else str(digest),
                volume=None if volume is None else str(volume),
                path=None if path is None else str(path),
                state=str(state),
            )
        )
    return tuple(rows)


async def _read_resources(
    conn: AsyncConnection,
    kind: ResourceKind,
    overrides: Mapping[tuple[str, str], InventoryOverride],
) -> tuple[ResourceRow, ...]:
    rows: list[ResourceRow] = []
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT name, cost_class, pool, host_uri, capabilities "
            "FROM resources WHERE kind = %s AND managed_by = %s AND name IS NOT NULL",
            (kind.value, _CONFIG_MANAGED_BY),
        )
        fetched = await cur.fetchall()
    for name, cost_class, pool, host_uri, capabilities in fetched:
        if _is_removed(overrides, kind.value, str(name)):
            continue
        caps = capabilities if isinstance(capabilities, dict) else {}
        rows.append(
            ResourceRow(
                name=str(name),
                cost_class=str(cost_class),
                pool=str(pool),
                host_uri=str(host_uri),
                vcpus=_opt_cap_int(caps, VCPUS_KEY),
                memory_mb=_opt_cap_int(caps, MEMORY_MB_KEY),
                concurrent_allocation_cap=_cap_int(caps, CONCURRENT_ALLOCATION_CAP_KEY, name=name),
                seed=_opt_cap_int(caps, "seed"),
            )
        )
    return tuple(rows)


async def _read_build_hosts(
    conn: AsyncConnection, overrides: Mapping[tuple[str, str], InventoryOverride]
) -> tuple[BuildHostRow, ...]:
    rows: list[BuildHostRow] = []
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT name, kind, base_image_volume, workspace_root, max_concurrent "
            "FROM build_hosts WHERE managed_by = %s",
            (_CONFIG_MANAGED_BY,),
        )
        fetched = await cur.fetchall()
    for name, kind, base_image_volume, workspace_root, max_concurrent in fetched:
        if _is_removed(overrides, BUILD_HOST_RESOURCE_KIND, str(name)):
            continue
        rows.append(
            BuildHostRow(
                name=str(name),
                kind=str(kind),
                base_image_volume=None if base_image_volume is None else str(base_image_volume),
                workspace_root=str(workspace_root),
                max_concurrent=int(max_concurrent),
            )
        )
    return tuple(rows)


async def _read_cost_classes(conn: AsyncConnection) -> tuple[tuple[str, Decimal], ...]:
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT cost_class, coeff FROM cost_class_coefficients ORDER BY cost_class"
        )
        fetched = await cur.fetchall()
    return tuple((str(name), Decimal(coeff)) for name, coeff in fetched)


def _cap_int(caps: dict[str, object], key: str, *, name: object) -> int:
    value = caps.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"resource {name!r} capability {key!r} is not an integer: {value!r}")
    return value


def _opt_cap_int(caps: dict[str, object], key: str) -> int | None:
    value = caps.get(key)
    if value is None:
        return None
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"capability {key!r} is not an integer: {value!r}")
    return value
