"""Offline shell completion over the merged ``kdivectl`` verb surface (ADR-0424).

A static walk of :func:`kdive.cli.__main__.build_parser` — the single constructor of the whole
curated + generated verb tree (ADR-0421) — records, for each subcommand path, the tokens
completable *at* that path: a group's child verbs plus the inherited ``--json``, a leaf verb's
``--`` flags, and the root's subcommands. The tree is baked into a self-contained bash or zsh
script (no ``argcomplete``/``shtab`` dependency, no per-keystroke Python), so completion resolves
groups/verbs/flags entirely offline with no bearer token: building the parser touches no
``Session`` and no network.
"""

from __future__ import annotations

import argparse
import re
from typing import cast

#: The root path key (an empty subcommand path) in the Python completion tree.
_ROOT = ""

#: The shell associative-array key the root path maps to. bash rejects an empty subscript, so the
#: root is keyed by a sentinel no subcommand path can contain (a ``/`` never appears in a token).
_ROOT_KEY = "/"

#: A token (subcommand name or long flag) safe to embed unquoted in the shell scripts. The whole
#: surface derives from tool names and parameter names (``[a-z0-9-]``) plus ``--`` flags, so a token
#: outside this set signals an unexpected parser shape and fails fast rather than emitting a script
#: with an injection or splitting hazard.
_SAFE_TOKEN = re.compile(r"^--?[A-Za-z0-9][A-Za-z0-9_-]*$|^[A-Za-z0-9][A-Za-z0-9_-]*$")


def build_completion_tree(parser: argparse.ArgumentParser) -> dict[str, list[str]]:
    """Walk ``parser`` into ``{space-joined path: sorted completable tokens}`` (ADR-0424).

    The root path is the empty string; a group path is its name; a verb path is
    ``"group verb"``. Each value is the sorted, de-duplicated set of long (``--``) options
    declared at that path plus the names of its immediate subcommands. Subparser aliases that
    point at the same parser object are walked once.

    Args:
        parser: A fully-constructed ``kdivectl`` parser (from ``build_parser``).

    Returns:
        A mapping from every reachable subcommand path to the tokens completable at it.

    Raises:
        ValueError: If a subcommand name or option is not a shell-safe token.
    """
    tree: dict[str, list[str]] = {}
    _walk(parser, _ROOT, tree)
    return tree


def _walk(parser: argparse.ArgumentParser, path: str, tree: dict[str, list[str]]) -> None:
    """Record ``path``'s completable tokens in ``tree`` and recurse into its subcommands."""
    tokens: set[str] = set()
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser] | None = None
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            subparsers = cast("argparse._SubParsersAction[argparse.ArgumentParser]", action)
            continue
        tokens.update(opt for opt in action.option_strings if opt.startswith("--"))
    if subparsers is not None:
        tokens.update(subparsers.choices)
    for token in tokens:
        if not _SAFE_TOKEN.match(token):
            raise ValueError(f"completion token {token!r} at path {path!r} is not shell-safe")
    tree[path] = sorted(tokens)
    if subparsers is None:
        return
    seen: set[int] = set()
    for name, subparser in subparsers.choices.items():
        if id(subparser) in seen:
            continue
        seen.add(id(subparser))
        _walk(subparser, f"{path} {name}".strip(), tree)


def render_completion(shell: str) -> str:
    """Return the completion script for ``shell`` (``"bash"`` or ``"zsh"``), built offline.

    Constructs the parser (no ``Session``, no network, no token) and bakes its static walk into
    a self-contained script. Argparse choices already constrain ``shell`` to the two supported
    values before this is reached.
    """
    from kdive.cli.__main__ import build_parser

    tree = build_completion_tree(build_parser())
    if shell == "bash":
        return _render_bash(tree)
    return _render_zsh(tree)


def _shell_key(path: str) -> str:
    """Map a tree path to its shell associative-array key (the root uses the ``/`` sentinel)."""
    return _ROOT_KEY if path == _ROOT else path


def _render_bash(tree: dict[str, list[str]]) -> str:
    entries = "\n".join(
        f'        ["{_shell_key(path)}"]="{" ".join(tokens)}"'
        for path, tokens in sorted(tree.items())
    )
    return f"""\
# kdivectl bash completion — generated by `kdivectl completion bash` (ADR-0424).
# Install: kdivectl completion bash > ~/.local/share/bash-completion/completions/kdivectl
_kdivectl() {{
    local -A _tree=(
{entries}
    )
    local cur path trial word i
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    path="{_ROOT_KEY}"
    for (( i = 1; i < COMP_CWORD; i++ )); do
        word="${{COMP_WORDS[i]}}"
        [[ $word == -* ]] && continue
        if [[ $path == "{_ROOT_KEY}" ]]; then trial="$word"; else trial="$path $word"; fi
        [[ -n ${{_tree[$trial]+set}} ]] && path="$trial"
    done
    mapfile -t COMPREPLY < <(compgen -W "${{_tree[$path]}}" -- "$cur")
}}
complete -F _kdivectl kdivectl
"""


def _render_zsh(tree: dict[str, list[str]]) -> str:
    entries = "\n".join(
        f"        '{_shell_key(path)}' '{' '.join(tokens)}'"
        for path, tokens in sorted(tree.items())
    )
    return f"""\
#compdef kdivectl
# kdivectl zsh completion — generated by `kdivectl completion zsh` (ADR-0424).
# Install (either works):
#   kdivectl completion zsh > "${{fpath[1]}}/_kdivectl"   # autoload, then restart the shell
#   source <(kdivectl completion zsh)                     # from ~/.zshrc, after compinit
_kdivectl() {{
    local -A _tree
    _tree=(
{entries}
    )
    local path trial word
    local -a before candidates
    before=( ${{words[2,CURRENT-1]}} )
    path="{_ROOT_KEY}"
    for word in $before; do
        [[ $word == -* ]] && continue
        if [[ $path == "{_ROOT_KEY}" ]]; then trial="$word"; else trial="$path $word"; fi
        (( ${{+_tree[$trial]}} )) && path="$trial"
    done
    candidates=( ${{=_tree[$path]}} )
    compadd -a candidates
}}
# Autoloaded from $fpath: zsh runs this file as the function itself. Sourced: register instead.
if [ "$funcstack[1]" = "_kdivectl" ]; then
    _kdivectl "$@"
else
    compdef _kdivectl kdivectl
fi
"""
