apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdive.fullname" . }}-worker-credential-broker
  labels:
    {{- include "kdive.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "kdive.fullname" . }}-reconciler
  ports:
    - name: tls
      port: {{ .Values.workerCredentialBroker.port }}
      targetPort: worker-credential-broker
      protocol: TCP
