"""Generate the per-namespace tool reference from the live FastMCP registry (ADR-0047).

Run via `just docs` (write) / `just docs-check` (verify). The core is a pure
function over the registry's tool objects; it fails loudly on incomplete
metadata rather than emitting blanks.
"""

from __future__ import annotations

import asyncio
import json
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from fastmcp.server.auth.providers.jwt import JWTVerifier, RSAKeyPair
from psycopg_pool import AsyncConnectionPool

from kdive.mcp.app import build_app
from kdive.security.secrets.secret_registry import SecretRegistry

_HEADER = "<!-- generated by scripts/gen_tool_reference.py; do not edit. Regenerate: just docs -->"
_REF_DIR = Path(__file__).resolve().parents[1] / "docs" / "guide" / "reference"


# Semantic recursion bound for the schema renderer (ADR-0177 decision 1). It counts
# semantic descent — into `properties` values, array `items`, and `anyOf`/`oneOf`
# variants — not raw JSON dict/list nesting. The deepest live tool parameter
# (`systems.define.profile`) measures 7 levels; 12 leaves headroom. A future deeper
# schema trips `test_max_schema_depth_clears_live_schemas` before it trips doc-gen.
_MAX_SCHEMA_DEPTH = 12

_SCALAR_TYPES = frozenset({"string", "integer", "number", "boolean", "null"})


def _is_structured(spec: dict[str, Any]) -> bool:
    """Whether a subschema carries structure the renderer must expand (ADR-0177)."""
    return any(key in spec for key in ("properties", "items", "enum", "anyOf", "oneOf"))


def render_schema_type(spec: dict[str, Any], depth: int = 0) -> str:
    """Render a one-line inline type summary for a JSON-Schema subschema (ADR-0177).

    Walks scalars, ``enum``/``const``, ``anyOf``/``oneOf`` unions (collapsing the Pydantic
    ``[T, null]`` optional pair to ``T (nullable)``), arrays, and objects. Raises
    ``ValueError`` on an unresolved ``$ref``/``$defs`` node or past ``_MAX_SCHEMA_DEPTH``
    rather than silently emitting a bare ``any``/``object``.
    """
    if depth > _MAX_SCHEMA_DEPTH:
        raise ValueError(f"schema nesting exceeds _MAX_SCHEMA_DEPTH={_MAX_SCHEMA_DEPTH}")
    if "$ref" in spec or "$defs" in spec:
        raise ValueError("schema renderer cannot resolve $ref/$defs; inline the schema")
    if "const" in spec:
        return f"`={spec['const']}`"
    enum = spec.get("enum")
    if isinstance(enum, list):
        return ", ".join(f"`{value}`" for value in enum)
    for union_key in ("anyOf", "oneOf"):
        variants = spec.get(union_key)
        if isinstance(variants, list) and variants:
            rendered = [render_schema_type(v, depth + 1) for v in variants]
            non_null = [v for v in rendered if v != "null"]
            if len(rendered) == 2 and len(non_null) == 1:
                return f"{non_null[0]} (nullable)"
            return " \\| ".join(rendered)
    type_ = spec.get("type")
    if type_ == "array":
        items = spec.get("items")
        inner = render_schema_type(items, depth + 1) if isinstance(items, dict) else "any"
        return f"array<{inner}>"
    if type_ == "object" or "properties" in spec:
        if "properties" not in spec:
            return _open_object_label(spec, depth)
        return _object_label(spec)
    if isinstance(type_, str) and type_ in _SCALAR_TYPES:
        return type_
    return "any"


def _open_object_label(spec: dict[str, Any], depth: int) -> str:
    """Render an object that declares no ``properties`` (a typed map or a free-form object).

    ``additionalProperties: {schema}`` is a dictionary keyed by string → that value type
    (``map<string, string>``); ``additionalProperties: true``/absent is a deliberately
    open object (``object(free-form)``). Either is an honest, fully-resolved shape — not a
    dropped-structure collapse — so the docs guard accepts it.
    """
    extra = spec.get("additionalProperties")
    if isinstance(extra, dict):
        return f"map<string, {render_schema_type(extra, depth + 1)}>"
    return "object(free-form)"


def _object_label(spec: dict[str, Any]) -> str:
    """Label an object subschema by its discriminating ``const`` field when it has one.

    Discriminated-union variants (rootfs/config/source) carry a ``const`` on a key like
    ``kind`` or ``source``; surfacing it (``object(kind=catalog)``) tells an agent which
    variant a sub-list block describes instead of an undifferentiated ``object``. A
    discriminator key (``kind``/``source``/``type``) wins over an incidental ``const`` like
    ``schema_version`` so the label names the axis the variants actually differ on.
    """
    props = spec.get("properties") or {}
    const_keys = [k for k, f in props.items() if isinstance(f, dict) and "const" in f]
    if not const_keys:
        return "object"
    preferred = next((k for k in ("kind", "source", "type") if k in const_keys), const_keys[0])
    return f"object({preferred}={props[preferred]['const']})"


def render_param_detail(spec: dict[str, Any], depth: int = 0) -> tuple[str, ...]:
    """Render the indented Markdown sub-list for a structured subschema's fields (ADR-0177).

    Object fields and array-item / union-variant object fields recurse into nested
    bullet lists; scalars and bare enums produce no sub-list (their inline type already
    carries the detail).
    """
    if depth > _MAX_SCHEMA_DEPTH:
        raise ValueError(f"schema nesting exceeds _MAX_SCHEMA_DEPTH={_MAX_SCHEMA_DEPTH}")
    indent = "  " * depth
    lines: list[str] = []
    variants = _object_variants(spec)
    label_variants = len(variants) > 1
    for variant in variants:
        if label_variants:
            lines.append(f"{indent}- _variant {_object_label(variant)}:_")
        field_indent = f"{indent}  " if label_variants else indent
        props = variant.get("properties", {})
        required = set(variant.get("required", []))
        for name, field in props.items():
            req = "required" if name in required else "optional"
            field_type = render_schema_type(field, depth + 1)
            desc = (field.get("description") or "").replace("\n", " ").strip()
            suffix = f" — {desc}" if desc else ""
            lines.append(f"{field_indent}- `{name}` (`{field_type}`, {req}){suffix}")
            extra_depth = depth + (2 if label_variants else 1)
            lines.extend(render_param_detail(field, extra_depth))
    items = spec.get("items")
    if isinstance(items, dict) and _is_structured(items):
        lines.extend(render_param_detail(items, depth + 1))
    return tuple(lines)


def _object_variants(spec: dict[str, Any]) -> list[dict[str, Any]]:
    """Object subschemas reachable from ``spec``: itself plus any union members.

    Descends through ``anyOf``/``oneOf`` (a field may be ``anyOf: [oneOf: [...], null]``),
    collecting every member that carries ``properties``. ``null`` and bare-scalar members
    drop out so a ``[T, null]`` optional contributes only ``T``'s fields.
    """
    variants: list[dict[str, Any]] = []
    if "properties" in spec:
        variants.append(spec)
    for union_key in ("anyOf", "oneOf"):
        for member in spec.get(union_key, []) or []:
            if isinstance(member, dict):
                variants.extend(_object_variants(member))
    return variants


@dataclass(frozen=True)
class ParamDoc:
    name: str
    type: str
    required: bool
    description: str
    detail: tuple[str, ...] = ()
    examples: tuple[Any, ...] = ()


@dataclass(frozen=True)
class MaturityDetail:
    """Why a `partial` tool is not yet `implemented` (ADR-0175)."""

    reason: str
    detail: str
    promotion: str
    providers: str | None = None


@dataclass(frozen=True)
class ToolDoc:
    name: str
    namespace: str
    description: str
    maturity: str
    read_only: bool
    destructive: bool
    params: tuple[ParamDoc, ...] = ()
    maturity_detail: MaturityDetail | None = None


_VALID_MATURITY_REASONS = {
    "provider_support",
    "live_dependency",
    "unproven_worker_path",
    "operator_gate",
    "degraded_stub",
}


def _maturity_detail(name: str, maturity: str, meta: dict[str, Any]) -> MaturityDetail | None:
    """Validate and lift the `maturity_detail` off ``meta`` (ADR-0175).

    A ``partial`` tool must carry a well-formed detail; a non-``partial`` tool must
    carry none. The generator raises here so ``just docs-check`` fails independently
    of the test suite.
    """
    raw = meta.get("maturity_detail")
    if maturity != "partial":
        if raw is not None:
            raise ValueError(f"{name}: non-partial tool carries a maturity_detail")
        return None
    if not isinstance(raw, dict):
        raise ValueError(f"{name}: partial tool has no maturity_detail")
    reason = raw.get("reason")
    if reason not in _VALID_MATURITY_REASONS:
        raise ValueError(f"{name}: invalid maturity reason {reason!r}")
    detail = (raw.get("detail") or "").strip()
    promotion = (raw.get("promotion") or "").strip()
    if not detail:
        raise ValueError(f"{name}: maturity_detail has no detail")
    if not promotion:
        raise ValueError(f"{name}: maturity_detail has no promotion")
    providers = raw.get("providers")
    providers = providers.strip() if isinstance(providers, str) else None
    return MaturityDetail(
        reason=reason, detail=detail, promotion=promotion, providers=providers or None
    )


def _params(schema: dict[str, Any]) -> tuple[ParamDoc, ...]:
    props = (schema or {}).get("properties", {})
    required = set((schema or {}).get("required", []))
    out: list[ParamDoc] = []
    for name, spec in props.items():
        detail = render_param_detail(spec) if _is_structured(spec) else ()
        examples = spec.get("examples")
        out.append(
            ParamDoc(
                name=name,
                type=render_schema_type(spec),
                required=name in required,
                description=(spec.get("description") or "").strip(),
                detail=detail,
                examples=tuple(examples) if isinstance(examples, list) else (),
            )
        )
    return tuple(out)


def tool_docs(tools: list[Any]) -> list[ToolDoc]:
    """Pure registry → ToolDoc list; raises ValueError on incomplete metadata."""
    docs: list[ToolDoc] = []
    for t in tools:
        if not (t.description or "").strip():
            raise ValueError(f"{t.name}: tool has no description")
        meta = t.meta or {}
        maturity = meta.get("maturity")
        if maturity not in {"implemented", "partial", "planned"}:
            raise ValueError(f"{t.name}: missing/invalid maturity {maturity!r}")
        maturity_detail = _maturity_detail(t.name, maturity, meta)
        params = _params(t.parameters)
        for p in params:
            if not p.description:
                raise ValueError(f"{t.name}:{p.name}: parameter has no description")
            if "\n" in p.description:
                raise ValueError(f"{t.name}:{p.name}: description has a table-breaking newline")
        ann = t.annotations
        docs.append(
            ToolDoc(
                name=t.name,
                namespace=t.name.split(".", 1)[0],
                description=t.description.strip(),
                maturity=maturity,
                read_only=bool(ann and ann.readOnlyHint),
                destructive=bool(ann and ann.destructiveHint),
                params=params,
                maturity_detail=maturity_detail,
            )
        )
    return docs


def _badges(d: ToolDoc) -> str:
    flags = [d.maturity]
    if d.read_only:
        flags.append("read-only")
    if d.destructive:
        flags.append("destructive")
    return " · ".join(f"`{f}`" for f in flags)


# Worked `build_profile` examples for runs.create (ADR-0177 decision 2). A pure constant —
# the gen script runs with a null pool and cannot call the Postgres-backed
# `runs.profile_examples`. `test_build_profile_examples_are_valid` pins each to
# `BuildProfile.parse`, so a schema change that invalidates a documented example fails loud.
_BUILD_PROFILE_EXAMPLES: tuple[tuple[str, dict[str, Any]], ...] = (
    (
        "external lane, recommended default (ingest a prebuilt artifact)",
        {"schema_version": 1, "source": "external"},
    ),
    (
        "server lane, warm-tree source (single-host convenience)",
        {"schema_version": 1, "source": "server", "kernel_source_ref": "v6.9"},
    ),
    (
        "server lane, git source",
        {
            "schema_version": 1,
            "source": "server",
            "kernel_source_ref": {
                "git": {"remote": "https://git.kernel.org/.../linux.git", "ref": "v6.9"}
            },
        },
    ),
)


def _build_profile_example_lines() -> list[str]:
    lines = ["`build_profile` examples:", ""]
    for label, payload in _BUILD_PROFILE_EXAMPLES:
        lines += [f"_{label}:_", "", "```json", json.dumps(payload, indent=2), "```", ""]
    return lines


def _tool_extras(tool_name: str) -> list[str]:
    """Per-tool worked examples / cross-links appended after the parameter table (ADR-0177)."""
    if tool_name == "runs.create":
        return _build_profile_example_lines()
    if tool_name in ("systems.define", "systems.provision"):
        return [
            "See [`systems.profile_examples`](systems.md#systemsprofile_examples) for a "
            "ready-to-edit `profile` example per configured provider.",
            "",
        ]
    return []


def _detail_lines(params: tuple[ParamDoc, ...]) -> list[str]:
    """The "Fields" sub-lists for any structured parameters, after the table."""
    lines: list[str] = []
    for p in sorted(params, key=lambda x: x.name):
        if p.detail:
            lines += [f"`{p.name}` fields:", "", *p.detail, ""]
    return lines


def _maturity_block(d: ToolDoc) -> list[str]:
    """The ADR-0175 maturity explanation, rendered under the badge for partial tools."""
    md = d.maturity_detail
    if md is None:
        return []
    lines = [
        f"**Maturity:** {md.reason} — {md.detail}",
        "",
        f"**Promotion:** {md.promotion}",
        "",
    ]
    if md.providers:
        lines += [f"**Provider support:** {md.providers}", ""]
    return lines


def _example_lines(params: tuple[ParamDoc, ...]) -> list[str]:
    """Render an Examples block for any parameter carrying schema ``examples``.

    The block sits below the parameter table (never inside a table cell), so a
    multi-line JSON example cannot break the Markdown table the way a piped or
    newline-bearing description would.
    """
    lines: list[str] = []
    for p in sorted(params, key=lambda x: x.name):
        if not p.examples:
            continue
        lines += [f"Examples for `{p.name}`:", ""]
        for example in p.examples:
            lines += ["```json", json.dumps(example, indent=2), "```", ""]
    return lines


def render_namespace(namespace: str, docs: list[ToolDoc]) -> str:
    lines = [_HEADER, "", f"# `{namespace}` tools", ""]
    for d in sorted(docs, key=lambda x: x.name):
        lines += [f"## `{d.name}`", "", _badges(d), "", *_maturity_block(d), d.description, ""]
        if d.params:
            lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
            for p in sorted(d.params, key=lambda x: x.name):
                req = "yes" if p.required else "no"
                cell = p.description.replace("|", "\\|")
                lines.append(f"| `{p.name}` | {p.type} | {req} | {cell} |")
            lines.append("")
            lines += _detail_lines(d.params)
            lines += _example_lines(d.params)
        lines += _tool_extras(d.name)
    return "\n".join(lines).rstrip() + "\n"


def render_index(docs: list[ToolDoc]) -> str:
    lines = [_HEADER, "", "# Tool reference", "", "| Tool | Maturity |", "|---|---|"]
    for d in sorted(docs, key=lambda x: x.name):
        lines.append(
            f"| [`{d.name}`]({d.namespace}.md#{d.name.replace('.', '')}) | `{d.maturity}` |"
        )
    return "\n".join(lines) + "\n"


def _registry_tools() -> list[Any]:
    pool = AsyncConnectionPool("postgresql://unused", open=False)
    kp = RSAKeyPair.generate()
    verifier = JWTVerifier(public_key=kp.public_key, issuer="https://gen.local", audience="kdive")
    app = build_app(pool, verifier=verifier, secret_registry=SecretRegistry())
    # The erased `list` cast is intentional: the generator only reads duck-typed
    # attributes (name/description/meta/annotations/parameters), so it needs none
    # of the concrete FunctionTool type the guard test casts to for `.fn`.
    return cast(list[Any], asyncio.run(app.list_tools()))


def _atomic_write_text(path: Path, text: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        delete=False,
    ) as handle:
        handle.write(text)
        tmp_path = Path(handle.name)
    try:
        tmp_path.replace(path)
    except OSError:
        tmp_path.unlink(missing_ok=True)
        raise


def write_reference(out_dir: Path) -> None:
    docs = tool_docs(_registry_tools())
    out_dir.mkdir(parents=True, exist_ok=True)
    by_ns: dict[str, list[ToolDoc]] = {}
    for d in docs:
        by_ns.setdefault(d.namespace, []).append(d)
    for ns, ns_docs in by_ns.items():
        _atomic_write_text(out_dir / f"{ns}.md", render_namespace(ns, ns_docs))
    _atomic_write_text(out_dir / "index.md", render_index(docs))


if __name__ == "__main__":
    write_reference(_REF_DIR)
    print(f"wrote reference to {_REF_DIR}", file=sys.stderr)
