"""Generate the per-namespace tool reference from the live FastMCP registry (ADR-0047).

Run via `just docs` (write) / `just docs-check` (verify). The core is a pure
function over the registry's tool objects; it fails loudly on incomplete
metadata rather than emitting blanks.
"""

from __future__ import annotations

import asyncio
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from fastmcp.server.auth.providers.jwt import JWTVerifier, RSAKeyPair
from psycopg_pool import AsyncConnectionPool

from kdive.mcp.app import build_app
from kdive.security.secrets.secret_registry import SecretRegistry

_HEADER = "<!-- generated by scripts/gen_tool_reference.py; do not edit. Regenerate: just docs -->"
_REF_DIR = Path(__file__).resolve().parents[1] / "docs" / "guide" / "reference"


@dataclass(frozen=True)
class ParamDoc:
    name: str
    type: str
    required: bool
    description: str


@dataclass(frozen=True)
class MaturityDetail:
    """Why a `partial` tool is not yet `implemented` (ADR-0175)."""

    reason: str
    detail: str
    promotion: str
    providers: str | None = None


@dataclass(frozen=True)
class ToolDoc:
    name: str
    namespace: str
    description: str
    maturity: str
    read_only: bool
    destructive: bool
    params: tuple[ParamDoc, ...] = ()
    maturity_detail: MaturityDetail | None = None


_VALID_MATURITY_REASONS = {
    "provider_support",
    "live_dependency",
    "unproven_worker_path",
    "operator_gate",
    "degraded_stub",
}


def _maturity_detail(name: str, maturity: str, meta: dict[str, Any]) -> MaturityDetail | None:
    """Validate and lift the `maturity_detail` off ``meta`` (ADR-0175).

    A ``partial`` tool must carry a well-formed detail; a non-``partial`` tool must
    carry none. The generator raises here so ``just docs-check`` fails independently
    of the test suite.
    """
    raw = meta.get("maturity_detail")
    if maturity != "partial":
        if raw is not None:
            raise ValueError(f"{name}: non-partial tool carries a maturity_detail")
        return None
    if not isinstance(raw, dict):
        raise ValueError(f"{name}: partial tool has no maturity_detail")
    reason = raw.get("reason")
    if reason not in _VALID_MATURITY_REASONS:
        raise ValueError(f"{name}: invalid maturity reason {reason!r}")
    detail = (raw.get("detail") or "").strip()
    promotion = (raw.get("promotion") or "").strip()
    if not detail:
        raise ValueError(f"{name}: maturity_detail has no detail")
    if not promotion:
        raise ValueError(f"{name}: maturity_detail has no promotion")
    providers = raw.get("providers")
    providers = providers.strip() if isinstance(providers, str) else None
    return MaturityDetail(
        reason=reason, detail=detail, promotion=promotion, providers=providers or None
    )


def _params(schema: dict[str, Any]) -> tuple[ParamDoc, ...]:
    props = (schema or {}).get("properties", {})
    required = set((schema or {}).get("required", []))
    out: list[ParamDoc] = []
    for name, spec in props.items():
        out.append(
            ParamDoc(
                name=name,
                type=str(spec.get("type", "any")),
                required=name in required,
                description=(spec.get("description") or "").strip(),
            )
        )
    return tuple(out)


def tool_docs(tools: list[Any]) -> list[ToolDoc]:
    """Pure registry → ToolDoc list; raises ValueError on incomplete metadata."""
    docs: list[ToolDoc] = []
    for t in tools:
        if not (t.description or "").strip():
            raise ValueError(f"{t.name}: tool has no description")
        meta = t.meta or {}
        maturity = meta.get("maturity")
        if maturity not in {"implemented", "partial", "planned"}:
            raise ValueError(f"{t.name}: missing/invalid maturity {maturity!r}")
        maturity_detail = _maturity_detail(t.name, maturity, meta)
        params = _params(t.parameters)
        for p in params:
            if not p.description:
                raise ValueError(f"{t.name}:{p.name}: parameter has no description")
            if "|" in p.description or "\n" in p.description:
                raise ValueError(
                    f"{t.name}:{p.name}: description has a table-breaking character (| or newline)"
                )
        ann = t.annotations
        docs.append(
            ToolDoc(
                name=t.name,
                namespace=t.name.split(".", 1)[0],
                description=t.description.strip(),
                maturity=maturity,
                read_only=bool(ann and ann.readOnlyHint),
                destructive=bool(ann and ann.destructiveHint),
                params=params,
                maturity_detail=maturity_detail,
            )
        )
    return docs


def _badges(d: ToolDoc) -> str:
    flags = [d.maturity]
    if d.read_only:
        flags.append("read-only")
    if d.destructive:
        flags.append("destructive")
    return " · ".join(f"`{f}`" for f in flags)


def _maturity_block(d: ToolDoc) -> list[str]:
    """The ADR-0175 maturity explanation, rendered under the badge for partial tools."""
    md = d.maturity_detail
    if md is None:
        return []
    lines = [
        f"**Maturity:** {md.reason} — {md.detail}",
        "",
        f"**Promotion:** {md.promotion}",
        "",
    ]
    if md.providers:
        lines += [f"**Provider support:** {md.providers}", ""]
    return lines


def render_namespace(namespace: str, docs: list[ToolDoc]) -> str:
    lines = [_HEADER, "", f"# `{namespace}` tools", ""]
    for d in sorted(docs, key=lambda x: x.name):
        lines += [f"## `{d.name}`", "", _badges(d), "", *_maturity_block(d), d.description, ""]
        if d.params:
            lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
            for p in sorted(d.params, key=lambda x: x.name):
                req = "yes" if p.required else "no"
                lines.append(f"| `{p.name}` | `{p.type}` | {req} | {p.description} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_index(docs: list[ToolDoc]) -> str:
    lines = [_HEADER, "", "# Tool reference", "", "| Tool | Maturity |", "|---|---|"]
    for d in sorted(docs, key=lambda x: x.name):
        lines.append(
            f"| [`{d.name}`]({d.namespace}.md#{d.name.replace('.', '')}) | `{d.maturity}` |"
        )
    return "\n".join(lines) + "\n"


def _registry_tools() -> list[Any]:
    pool = AsyncConnectionPool("postgresql://unused", open=False)
    kp = RSAKeyPair.generate()
    verifier = JWTVerifier(public_key=kp.public_key, issuer="https://gen.local", audience="kdive")
    app = build_app(pool, verifier=verifier, secret_registry=SecretRegistry())
    # The erased `list` cast is intentional: the generator only reads duck-typed
    # attributes (name/description/meta/annotations/parameters), so it needs none
    # of the concrete FunctionTool type the guard test casts to for `.fn`.
    return cast(list[Any], asyncio.run(app.list_tools()))


def _atomic_write_text(path: Path, text: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        delete=False,
    ) as handle:
        handle.write(text)
        tmp_path = Path(handle.name)
    try:
        tmp_path.replace(path)
    except OSError:
        tmp_path.unlink(missing_ok=True)
        raise


def write_reference(out_dir: Path) -> None:
    docs = tool_docs(_registry_tools())
    out_dir.mkdir(parents=True, exist_ok=True)
    by_ns: dict[str, list[ToolDoc]] = {}
    for d in docs:
        by_ns.setdefault(d.namespace, []).append(d)
    for ns, ns_docs in by_ns.items():
        _atomic_write_text(out_dir / f"{ns}.md", render_namespace(ns, ns_docs))
    _atomic_write_text(out_dir / "index.md", render_index(docs))


if __name__ == "__main__":
    write_reference(_REF_DIR)
    print(f"wrote reference to {_REF_DIR}", file=sys.stderr)
