"""Generate the role→tool visibility matrix in docs/guide/safety-and-rbac.md (#347).

The matrix is rendered from the canonical authorization classification in
:mod:`kdive.mcp.exposure` (the same ``tool_visible`` rule ``ToolExposureMiddleware`` applies
to ``list_tools``), so the documented table cannot drift from what the server actually
advertises. Run via ``just rbac-matrix`` (write) / ``just rbac-matrix-check`` (verify).

The generated region is delimited by HTML comment markers in the doc; only the text between
them is replaced, so the surrounding prose is hand-maintained. ``--check`` re-renders and
diffs against the committed region, exiting non-zero on drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

from kdive.mcp.exposure import (
    CLASSIFIED_TOOLS,
    PUBLIC_TOOLS,
    ExposureScope,
    required_scopes,
    tool_visible,
)
from kdive.security.authz.context import RequestContext
from kdive.security.authz.rbac import PlatformRole, Role

_ROOT = Path(__file__).resolve().parents[1]
_DOC = _ROOT / "docs" / "guide" / "safety-and-rbac.md"

BEGIN_MARKER = "<!-- BEGIN GENERATED: rbac-tool-matrix (just rbac-matrix) -->"
END_MARKER = "<!-- END GENERATED: rbac-tool-matrix -->"

#: Single-grant profiles, in column order. A real token holding several grants sees the union.
_PROFILES: tuple[tuple[str, RequestContext], ...] = (
    ("Viewer", RequestContext("p", None, ("proj",), {"proj": Role.VIEWER})),
    ("Contributor", RequestContext("p", None, ("proj",), {"proj": Role.CONTRIBUTOR})),
    ("Operator", RequestContext("p", None, ("proj",), {"proj": Role.OPERATOR})),
    ("Admin", RequestContext("p", None, ("proj",), {"proj": Role.ADMIN})),
    ("Plat-Op", RequestContext("p", None, (), {}, frozenset({PlatformRole.PLATFORM_OPERATOR}))),
    ("Plat-Aud", RequestContext("p", None, (), {}, frozenset({PlatformRole.PLATFORM_AUDITOR}))),
    ("Plat-Adm", RequestContext("p", None, (), {}, frozenset({PlatformRole.PLATFORM_ADMIN}))),
)

_SCOPE_LABEL: dict[ExposureScope, str] = {
    ExposureScope.PROJECT_VIEWER: "viewer",
    ExposureScope.PROJECT_CONTRIBUTOR: "contributor",
    ExposureScope.PROJECT_OPERATOR: "operator",
    ExposureScope.PROJECT_ADMIN: "admin",
    ExposureScope.PLATFORM_OPERATOR: "plat-operator",
    ExposureScope.PLATFORM_ADMIN: "plat-admin",
    ExposureScope.PLATFORM_AUDITOR: "plat-auditor",
}


def _scope_label(tool: str) -> str:
    """A human label for a tool's any-of scope set; public tools render as ``(public)``."""
    scopes = required_scopes(tool)
    if not scopes:
        return "*(public)*"
    return " / ".join(sorted(_SCOPE_LABEL[scope] for scope in scopes))


def _all_tools() -> list[str]:
    return sorted(CLASSIFIED_TOOLS | PUBLIC_TOOLS)


def _summary_table(tools: list[str]) -> list[str]:
    rows = ["| Profile | Tools visible |", "|---|--:|"]
    for name, ctx in _PROFILES:
        count = sum(tool_visible(tool, ctx) for tool in tools)
        rows.append(f"| {name} | {count} |")
    rows.append(f"| (any authenticated token) | {len(PUBLIC_TOOLS)} public |")
    return rows


def _matrix_table(tools: list[str]) -> list[str]:
    cols = " | ".join(name for name, _ in _PROFILES)
    rows = [f"| Tool | Scope (any-of) | {cols} |", "|---|---|" + ":-:|" * len(_PROFILES)]
    for tool in tools:
        cells = " | ".join("✓" if tool_visible(tool, ctx) else "" for _, ctx in _PROFILES)
        rows.append(f"| `{tool}` | {_scope_label(tool)} | {cells} |")
    return rows


def render() -> str:
    """Render the generated region body (between the markers, markers excluded)."""
    tools = _all_tools()
    lines = [
        "<!-- This table is generated by scripts/gen_rbac_tool_matrix.py from",
        "     kdive.mcp.exposure. Do not edit by hand; run `just rbac-matrix`. -->",
        "",
        f"Computed from the live `tool_visible` rule over all {len(tools)} registered tools.",
        "Columns are single-grant profiles; a token holding several grants sees the union.",
        "Project roles are cumulative (`viewer < contributor < operator < admin`); the platform",
        "tier is a separate axis (`plat-admin` implies `plat-auditor` only). Public tools are",
        "visible to every authenticated token regardless of grants.",
        "",
        *_summary_table(tools),
        "",
        *_matrix_table(tools),
    ]
    return "\n".join(lines)


def splice(doc_text: str, block: str) -> str:
    """Replace the text between the markers in ``doc_text`` with ``block``.

    Raises:
        SystemExit: a marker is missing or the END marker precedes the BEGIN marker.
    """
    start = doc_text.find(BEGIN_MARKER)
    end = doc_text.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(f"missing or malformed rbac-tool-matrix markers in {_DOC}")
    head = doc_text[: start + len(BEGIN_MARKER)]
    tail = doc_text[end:]
    return f"{head}\n{block}\n{tail}"


def write(doc_path: Path = _DOC) -> None:
    """Re-render the matrix and splice it into the marked region of ``doc_path``."""
    doc_path.write_text(splice(doc_path.read_text(encoding="utf-8"), render()), encoding="utf-8")


def check(doc_path: Path = _DOC) -> int:
    """Return 0 when the committed region matches a fresh render, 1 otherwise."""
    current = doc_path.read_text(encoding="utf-8")
    if splice(current, render()) == current:
        print("rbac-tool-matrix: in sync.")
        return 0
    print(
        "rbac-tool-matrix is stale — run 'just rbac-matrix' and commit "
        "docs/guide/safety-and-rbac.md",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str]) -> int:
    if argv and argv[0] == "--check":
        return check()
    write()
    print(f"wrote the rbac-tool-matrix into {_DOC}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
