"""Generate the committed ``kdivectl`` verb descriptors from the live tool schemas.

Epic #1442 entry 4 (R5/R6). Mirrors :mod:`scripts.gen_tool_reference`: build the app,
read ``list_tools()``, and run a pure transform over the schemas — here into a tuple of
:class:`kdive.cli.commands.verb_spec.GeneratedVerb` written to the committed module
:mod:`kdive.cli.commands._generated_verbs`. The parser-merge (#1448), generic dispatch
(#1450), and ``--param-json`` escape (#1449) are separate downstream entries; this
generator only emits the descriptor data.

Per parameter (after unwrapping the Pydantic ``[T, null]`` optional wrapper): JSON-Schema
``type`` -> argparse type (``string``/``integer``/``number`` -> ``str``/``int``/``float``,
``boolean`` -> ``store_true``); ``enum`` -> ``choices``; array-of-string -> ``append``;
``required`` -> ``required=True``; ``description`` -> flag help. Flag names come from
:func:`kdive.cli.reserved_flags.derive_cli_flag`; a parameter that would derive to a
:data:`RESERVED_CLI_FLAGS` name is a generation error.

The ~20 tools whose sole parameter is a ``request`` wrapper object expose that object's
scalar body fields as flat flags (``unwrap_request=True``); a re-wrap under a single
``request`` key happens at call time (#1450). Non-scalar parameters (nested objects,
object arrays, tuple/typeless arrays, scalar unions) get no flag and are recorded in
``json_params`` for the #1449 escape.

Run via ``just cli-verbs`` (write) / ``just cli-verbs-check`` (verify; joins ``just ci``).
"""

from __future__ import annotations

import asyncio
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, cast

from fastmcp.server.auth.providers.jwt import JWTVerifier, RSAKeyPair
from psycopg_pool import AsyncConnectionPool

from kdive.cli.commands.verb_spec import GeneratedFlag, GeneratedVerb
from kdive.cli.reserved_flags import RESERVED_CLI_FLAGS, derive_cli_flag
from kdive.mcp.assembly.app import build_app
from kdive.security.secrets.secret_registry import SecretRegistry

_COMMANDS_DIR = Path(__file__).resolve().parents[1] / "src" / "kdive" / "cli" / "commands"
_MODULE = _COMMANDS_DIR / "_generated_verbs.py"

_HEADER = '''\
"""GENERATED by scripts/gen_cli_verbs.py; do not edit. Regenerate: just cli-verbs.

The schema-derived ``kdivectl`` verb descriptors, one :class:`GeneratedVerb` per registered
MCP tool (epic #1442 R5/R6). ``just cli-verbs-check`` fails when this is stale, so adding a
server tool without regenerating fails ``just ci``.
"""

from __future__ import annotations

from kdive.cli.commands.verb_spec import GeneratedFlag, GeneratedVerb

'''

_SCALAR_ARGTYPE = {"string": "str", "integer": "int", "number": "float"}


def _unwrap_optional(spec: dict[str, Any]) -> dict[str, Any] | None:
    """Collapse a Pydantic ``anyOf: [T, null]`` optional to ``T``; else return ``spec``.

    Returns ``None`` for a genuine multi-member union (e.g. ``number | string``), which has
    no single argparse type and is deferred to the ``--param-json`` escape (#1449).
    """
    variants = spec.get("anyOf")
    if not isinstance(variants, list):
        return spec
    non_null = [v for v in variants if isinstance(v, dict) and v.get("type") != "null"]
    return non_null[0] if len(non_null) == 1 else None


def _object_body(spec: dict[str, Any]) -> dict[str, Any] | None:
    """Return the object subschema of a ``request`` wrapper (``{object}`` or ``[object, null]``)."""
    body = _unwrap_optional(spec)
    if body is not None and "properties" in body:
        return body
    return None


def _flag_for(dest: str, spec: dict[str, Any], required: bool) -> GeneratedFlag | None:
    """Derive the ``--flag`` for a parameter, or ``None`` when it is not scalar-derivable.

    Raises:
        ValueError: The parameter derives to a reserved flag (should be impossible; the
            collision guard already asserts it, so this is a fail-loud backstop).
    """
    effective = _unwrap_optional(spec)
    if effective is None:
        return None
    flag = derive_cli_flag(dest)
    if flag in RESERVED_CLI_FLAGS:
        raise ValueError(f"parameter {dest!r} derives to reserved flag {flag}")
    help_ = " ".join((spec.get("description") or effective.get("description") or "").split())
    enum = effective.get("enum")
    if isinstance(enum, list):
        choices = tuple(str(v) for v in enum)
        return GeneratedFlag(flag, dest, required, help_, arg_type="str", choices=choices)
    type_ = effective.get("type")
    if type_ == "array":
        items = effective.get("items") or {}
        if items.get("type") == "string":
            return GeneratedFlag(flag, dest, required, help_, arg_type="str", action="append")
        return None
    if type_ == "boolean":
        return GeneratedFlag(flag, dest, required, help_, action="store_true")
    argtype = _SCALAR_ARGTYPE.get(type_) if isinstance(type_, str) else None
    if argtype is None:
        return None
    return GeneratedFlag(flag, dest, required, help_, arg_type=argtype)


def _verb_for(tool: Any) -> GeneratedVerb:
    """Transform one registered tool into its :class:`GeneratedVerb` descriptor."""
    group, op = tool.name.split(".", 1)
    ann = tool.annotations
    help_ = " ".join((tool.description or "").strip().split("\n")[0].split())
    schema = tool.parameters or {}
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    unwrap = set(props) == {"request"}
    if unwrap:
        body = _object_body(props["request"])
        if body is None:
            props, required = {}, set()
        else:
            props = body.get("properties", {})
            required = set(body.get("required", []))
    flags: list[GeneratedFlag] = []
    json_params: list[str] = []
    for name, spec in props.items():
        flag = _flag_for(name, spec, name in required)
        (json_params.append(name) if flag is None else flags.append(flag))
    return GeneratedVerb(
        group=group,
        sub=op.replace("_", "-"),
        tool=tool.name,
        read_only=bool(ann and ann.readOnlyHint),
        destructive=bool(ann and ann.destructiveHint),
        help=help_,
        unwrap_request=unwrap,
        flags=tuple(flags),
        json_params=tuple(json_params),
    )


def verb_specs(tools: list[Any]) -> list[GeneratedVerb]:
    """Pure registry -> sorted :class:`GeneratedVerb` list, one per tool."""
    return sorted((_verb_for(t) for t in tools), key=lambda v: v.tool)


def render_module(verbs: list[GeneratedVerb]) -> str:
    """Render the committed module source (unformatted; :func:`_ruff_format` canonicalizes).

    Each verb round-trips through its frozen-dataclass ``repr``, so the descriptor is a
    plain constructor call that reconstructs the exact object.
    """
    body = ",\n".join(f"    {verb!r}" for verb in verbs)
    return f"{_HEADER}GENERATED_VERBS: tuple[GeneratedVerb, ...] = (\n{body},\n)\n"


def _ruff_format(source: str) -> str:
    """Return ``source`` as ``ruff format`` would write it, so the artifact passes ``just lint``."""
    proc = subprocess.run(
        ["ruff", "format", "-"], input=source, capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise RuntimeError(f"ruff format failed on generated verbs:\n{proc.stderr}")
    return proc.stdout


def _registry_tools() -> list[Any]:
    # Offline schema extraction (mirrors gen_tool_reference): the pool never connects and the
    # dummy S3 endpoint is never reached; the app is built purely to read tool schemas.
    os.environ.setdefault("KDIVE_S3_ENDPOINT_URL", "http://minio.invalid:9000")
    os.environ.setdefault("KDIVE_S3_BUCKET", "kdive-docs")
    pool = AsyncConnectionPool("postgresql://unused", open=False)
    kp = RSAKeyPair.generate()
    verifier = JWTVerifier(public_key=kp.public_key, issuer="https://gen.local", audience="kdive")
    app = build_app(pool, verifier=verifier, secret_registry=SecretRegistry())
    return cast(list[Any], asyncio.run(app.list_tools()))


def build_module() -> str:
    """Build the fully formatted committed-module source from the live registry."""
    return _ruff_format(render_module(verb_specs(_registry_tools())))


def _atomic_write_text(path: Path, text: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as handle:
        handle.write(text)
        tmp_path = Path(handle.name)
    try:
        tmp_path.replace(path)
    except OSError:
        tmp_path.unlink(missing_ok=True)
        raise


def write_module(path: Path = _MODULE) -> None:
    """Regenerate the committed descriptor module at ``path``."""
    _atomic_write_text(path, build_module())


def check(path: Path = _MODULE) -> int:
    """Return 0 when the committed module matches a fresh generation, 1 (with advice) otherwise."""
    fresh = build_module()
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if fresh == current:
        print("cli-verbs: in sync.")
        return 0
    print(
        "generated CLI verbs are stale — run 'just cli-verbs' and commit "
        "src/kdive/cli/commands/_generated_verbs.py",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str]) -> int:
    if argv and argv[0] == "--check":
        return check()
    write_module()
    print(f"wrote {_MODULE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
