"""Generate docs/guide/reference/config.md from the config registry (ADR-0087).

Pure core (`render`) over the Setting list; the CLI writes the file. Mirrors
scripts/gen_tool_reference.py. Run via `just config-docs` / `just config-docs-check`.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence
from pathlib import Path

from kdive.config import all_settings
from kdive.config.registry import Setting, never_required

_HEADER = (
    "<!-- generated by scripts/gen_config_reference.py; do not edit. "
    "Regenerate: just config-docs -->"
)
_OUT = Path(__file__).resolve().parents[1] / "docs" / "guide" / "reference" / "config.md"


def _required_label(setting: Setting) -> str:
    if setting.required_when is never_required:
        return "no"
    return "yes" if setting.required_when({}) else "conditional"


def _value_label(setting: Setting) -> str:
    if setting.secret:
        return "secret (ref only)"
    return setting.help or "—"


def render(settings: Sequence[Setting]) -> str:
    """Render the settings to grouped Markdown (pure; deterministic)."""
    by_group: dict[str, list[Setting]] = {}
    for s in settings:
        by_group.setdefault(s.group, []).append(s)
    lines = [_HEADER, "", "# Configuration reference (`KDIVE_*`)", ""]
    for group in sorted(by_group):
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| Variable | Processes | Default | Required | Value |")
        lines.append("|----------|-----------|---------|----------|-------|")
        for s in sorted(by_group[group], key=lambda x: x.name):
            procs = ", ".join(sorted(s.processes)) or "—"
            default = "—" if s.default is None else f"`{s.default}`"
            lines.append(
                f"| `{s.name}` | {procs} | {default} | {_required_label(s)} | {_value_label(s)} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_reference(out: Path = _OUT) -> None:
    out.write_text(render(all_settings()), encoding="utf-8")


if __name__ == "__main__":
    write_reference()
    print(f"wrote {_OUT}", file=sys.stderr)
