"""Generate the committed ``kdivectl`` verb descriptors from the live tool schemas.

Epic #1442 entry 4 (R5/R6). Mirrors :mod:`scripts.gen_tool_reference`: build the app,
read ``list_tools()``, and run a pure transform over the schemas — here into a tuple of
:class:`kdive.cli.commands.verb_spec.GeneratedVerb` written to the committed module
:mod:`kdive.cli.commands._generated_verbs`. The parser-merge (#1448), generic dispatch
(#1450), and ``--param-json`` escape (#1449) are separate downstream entries; this
generator only emits the descriptor data.

Per parameter (after resolving any ``#/$defs`` reference and unwrapping the Pydantic
``[T, null]`` optional wrapper): JSON-Schema
``type`` -> argparse type (``string``/``integer``/``number`` -> ``str``/``int``/``float``,
``boolean`` -> ``store_true``); ``enum`` -> ``choices``; array-of-string -> ``append``;
``required`` -> ``required=True``; ``description`` -> flag help. Flag names come from
:func:`kdive.cli.reserved_flags.derive_cli_flag`; a parameter that would derive to a
:data:`RESERVED_CLI_FLAGS` name is a generation error.

The ~20 tools whose sole parameter is a ``request`` wrapper object expose that object's
scalar body fields as flat flags (``unwrap_request=True``); a re-wrap under a single
``request`` key happens at call time (#1450). Non-scalar parameters (nested objects,
object arrays, tuple/typeless arrays, scalar unions) get no flag and are recorded in
``json_params`` for the #1449 escape.

A tool that declares required parameters but derives neither a flag nor a JSON escape is a
generation error, not a silently argument-less verb: the drift check cannot catch that case
because it compares an empty generation against an equally empty commit (ADR-0469).

Run via ``just cli-verbs`` (write) / ``just cli-verbs-check`` (verify; joins ``just ci``).
"""

from __future__ import annotations

import asyncio
import subprocess
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path
from types import MappingProxyType
from typing import Any, cast

from fastmcp.server.auth.providers.jwt import JWTVerifier, RSAKeyPair
from psycopg_pool import AsyncConnectionPool

from kdive.cli.commands.verb_spec import GeneratedFlag, GeneratedVerb
from kdive.cli.reserved_flags import RESERVED_CLI_FLAGS, derive_cli_flag
from kdive.mcp.assembly.app import build_app
from kdive.mcp.assembly.schema_catalog import CatalogWorkerDeathVerifier
from kdive.security.secrets.secret_registry import SecretRegistry
from kdive.store.assembly import ObjectStoreAssembly
from kdive.store.objectstore import ObjectStore

_COMMANDS_DIR = Path(__file__).resolve().parents[1] / "src" / "kdive" / "cli" / "commands"
_MODULE = _COMMANDS_DIR / "_generated_verbs.py"

_HEADER = '''\
"""GENERATED by scripts/gen_cli_verbs.py; do not edit. Regenerate: just cli-verbs.

The schema-derived ``kdivectl`` verb descriptors, one :class:`GeneratedVerb` per registered
MCP tool (epic #1442 R5/R6). ``just cli-verbs-check`` fails when this is stale, so adding a
server tool without regenerating fails ``just ci``.
"""

from __future__ import annotations

from kdive.cli.commands.verb_spec import GeneratedFlag, GeneratedVerb

'''

_SCALAR_ARGTYPE = {"string": "str", "integer": "int", "number": "float"}

#: The empty ``$defs`` table, for schemas that define no reusable subschemas.
_NO_DEFS: Mapping[str, Any] = MappingProxyType({})

_REF_PREFIX = "#/$defs/"


def _resolve_ref(spec: dict[str, Any], defs: Mapping[str, Any]) -> dict[str, Any]:
    """Follow a local ``#/$defs/<name>`` reference to the subschema it names.

    fastmcp inlines most models, but a reused one — a ``StrEnum`` in particular — renders as a
    bare ``$ref``. Left unresolved that parameter looks typeless, so it loses its ``enum`` ->
    ``choices`` and falls through to the ``--<param>-json`` escape, which then rejects the bare
    string the enum actually wants (#1584, ADR-0469). Keywords spelled alongside the ``$ref``
    (a per-field ``description``) stay authoritative over the target's. A dangling or cyclic
    reference is returned unresolved rather than raising, so an unexpected schema shape
    degrades to the JSON escape instead of breaking generation.
    """
    seen: set[str] = set()
    while isinstance(ref := spec.get("$ref"), str) and ref.startswith(_REF_PREFIX):
        name = ref.removeprefix(_REF_PREFIX)
        target = defs.get(name)
        if name in seen or not isinstance(target, dict):
            return spec
        seen.add(name)
        spec = {**target, **{k: v for k, v in spec.items() if k != "$ref"}}
    return spec


def _unwrap_optional(
    spec: dict[str, Any], defs: Mapping[str, Any] = _NO_DEFS
) -> dict[str, Any] | None:
    """Collapse a Pydantic ``anyOf: [T, null]`` optional to ``T``; else return ``spec``.

    Returns ``None`` for a genuine multi-member union (e.g. ``number | string``), which has
    no single argparse type and is deferred to the ``--param-json`` escape (#1449).
    Both the wrapper and the surviving member are ``$ref``-resolved (:func:`_resolve_ref`).
    """
    spec = _resolve_ref(spec, defs)
    variants = spec.get("anyOf")
    if not isinstance(variants, list):
        return spec
    members = [_resolve_ref(v, defs) for v in variants if isinstance(v, dict)]
    non_null = [v for v in members if v.get("type") != "null"]
    return non_null[0] if len(non_null) == 1 else None


def _object_body(spec: dict[str, Any], defs: Mapping[str, Any] = _NO_DEFS) -> dict[str, Any] | None:
    """Return the object subschema of a ``request`` wrapper (``{object}`` or ``[object, null]``)."""
    body = _unwrap_optional(spec, defs)
    if body is not None and "properties" in body:
        return body
    return None


def _flag_for(
    dest: str, spec: dict[str, Any], required: bool, defs: Mapping[str, Any] = _NO_DEFS
) -> GeneratedFlag | None:
    """Derive the ``--flag`` for a parameter, or ``None`` when it is not scalar-derivable.

    Raises:
        ValueError: The parameter derives to a reserved flag (should be impossible; the
            collision guard already asserts it, so this is a fail-loud backstop).
    """
    effective = _unwrap_optional(spec, defs)
    if effective is None:
        return None
    flag = derive_cli_flag(dest)
    if flag in RESERVED_CLI_FLAGS:
        raise ValueError(f"parameter {dest!r} derives to reserved flag {flag}")
    help_ = " ".join((spec.get("description") or effective.get("description") or "").split())
    enum = effective.get("enum")
    if isinstance(enum, list):
        choices = tuple(str(v) for v in enum)
        return GeneratedFlag(flag, dest, required, help_, arg_type="str", choices=choices)
    type_ = effective.get("type")
    if type_ == "array":
        items = effective.get("items") or {}
        if items.get("type") == "string":
            return GeneratedFlag(flag, dest, required, help_, arg_type="str", action="append")
        return None
    if type_ == "boolean":
        # A required boolean must be able to express *false*, which ``store_true`` cannot:
        # its only two states are "flag given" (true) and "flag absent", and absent is not
        # a legal payload when the parameter is required. Such a flag pairs with a
        # ``--no-<flag>`` instead. An optional boolean keeps ``store_true`` so "unset"
        # stays distinguishable from an explicit false and the server default holds.
        action = "bool_optional" if required else "store_true"
        return GeneratedFlag(flag, dest, required, help_, action=action)
    argtype = _SCALAR_ARGTYPE.get(type_) if isinstance(type_, str) else None
    if argtype is None:
        return None
    return GeneratedFlag(flag, dest, required, help_, arg_type=argtype)


def _verb_for(tool: Any) -> GeneratedVerb:
    """Transform one registered tool into its :class:`GeneratedVerb` descriptor.

    Raises:
        ValueError: The tool declares required parameters but derives neither a flag nor a
            ``--<param>-json`` escape, which would emit an uninvokable verb (ADR-0469).
    """
    group, op = tool.name.split(".", 1)
    ann = tool.annotations
    help_ = " ".join((tool.description or "").strip().split("\n")[0].split())
    schema = tool.parameters or {}
    defs = schema.get("$defs") or _NO_DEFS
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    top_required = set(required)
    unwrap = set(props) == {"request"}
    if unwrap:
        body = _object_body(props["request"], defs)
        if body is None:
            # A ``request`` that is not a single object (a discriminated union such as
            # ``accounting.report``) has no body to flatten. Keep it as a whole-parameter
            # ``--request-json`` escape rather than emitting a verb with no way to pass the
            # required argument at all.
            unwrap = False
        else:
            props = body.get("properties", {})
            required = set(body.get("required", []))
    flags: list[GeneratedFlag] = []
    json_params: list[str] = []
    for name, spec in props.items():
        flag = _flag_for(name, spec, name in required, defs)
        if flag is None:
            json_params.append(name)
        else:
            flags.append(flag)
    if not flags and not json_params and (required or top_required):
        # An argument-less verb for a tool that demands arguments is uninvokable, and the
        # artifact drift check cannot see it: it compares an empty generation against an
        # equally empty commit and passes (#1588, ADR-0469).
        raise ValueError(
            f"{tool.name!r} requires {sorted(required or top_required)} but derives no flags "
            "and no --<param>-json escape; the verb would be uninvokable"
        )
    return GeneratedVerb(
        group=group,
        sub=op.replace("_", "-"),
        tool=tool.name,
        read_only=bool(ann and ann.readOnlyHint),
        destructive=bool(ann and ann.destructiveHint),
        help=help_,
        unwrap_request=unwrap,
        flags=tuple(flags),
        json_params=tuple(json_params),
    )


def verb_specs(tools: list[Any]) -> list[GeneratedVerb]:
    """Pure registry -> sorted :class:`GeneratedVerb` list, one per tool."""
    return sorted((_verb_for(t) for t in tools), key=lambda v: v.tool)


def render_module(verbs: list[GeneratedVerb]) -> str:
    """Render the committed module source (unformatted; :func:`_ruff_format` canonicalizes).

    Each verb round-trips through its frozen-dataclass ``repr``, so the descriptor is a
    plain constructor call that reconstructs the exact object.
    """
    body = ",\n".join(f"    {verb!r}" for verb in verbs)
    return f"{_HEADER}GENERATED_VERBS: tuple[GeneratedVerb, ...] = (\n{body},\n)\n"


def _ruff_format(source: str) -> str:
    """Return ``source`` as ``ruff format`` would write it, so the artifact passes ``just lint``."""
    proc = subprocess.run(
        ["ruff", "format", "-"], input=source, capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise RuntimeError(f"ruff format failed on generated verbs:\n{proc.stderr}")
    return proc.stdout


def _registry_tools() -> list[Any]:
    # Offline schema extraction (mirrors gen_tool_reference): the pool and injected store are
    # never invoked; the app is built purely to read tool schemas.
    pool = AsyncConnectionPool("postgresql://unused", open=False)
    kp = RSAKeyPair.generate()
    verifier = JWTVerifier(public_key=kp.public_key, issuer="https://gen.local", audience="kdive")
    object_stores = ObjectStoreAssembly(store=cast(ObjectStore, object()))
    app = build_app(
        pool,
        verifier=verifier,
        object_store_assembly=object_stores,
        secret_registry=SecretRegistry(),
        worker_death_verifier=CatalogWorkerDeathVerifier(),
    )
    return cast(list[Any], asyncio.run(app.list_tools()))


def build_module() -> str:
    """Build the fully formatted committed-module source from the live registry."""
    return _ruff_format(render_module(verb_specs(_registry_tools())))


def _atomic_write_text(path: Path, text: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as handle:
        handle.write(text)
        tmp_path = Path(handle.name)
    try:
        tmp_path.replace(path)
    except OSError:
        tmp_path.unlink(missing_ok=True)
        raise


def write_module(path: Path = _MODULE) -> None:
    """Regenerate the committed descriptor module at ``path``."""
    _atomic_write_text(path, build_module())


def check(path: Path = _MODULE) -> int:
    """Return 0 when the committed module matches a fresh generation, 1 (with advice) otherwise."""
    fresh = build_module()
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if fresh == current:
        print("cli-verbs: in sync.")
        return 0
    print(
        "generated CLI verbs are stale — run 'just cli-verbs' and commit "
        "src/kdive/cli/commands/_generated_verbs.py",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str]) -> int:
    if argv and argv[0] == "--check":
        return check()
    write_module()
    print(f"wrote {_MODULE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
